kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "jmeter-master"
spec:
  output:
    to:
      kind: ImageStreamTag
      name: jmeter-test-suite:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/digitalnerd/jmeter-jenkins-openshift.git
	type: Git
    contextDir: /
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: jmeter:latest
        namespace: performance
    type: Docker
status:
  lastVersion: 0
